language: php
sudo: false
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly
cache:
  directories:
    - $HOME/.composer/cache
install:
  - composer install --prefer-dist
script:
  - vendor/bin/phpunit tests
