language: php
sudo: false
php:
  - '5.5' # PHPUnit 4.8
  - '5.6' # PHPUnit 5.7
  - '7'   # PHPUnit 6.x
  - '7.1' # PHPUnit 7.x
  - '7.2' # PHPUnit 7.x
  - nightly
cache:
  directories:
    - $HOME/.composer/cache
install:
  - composer install --prefer-dist
script:
  - vendor/bin/phpunit test
